# Generated by Django 5.1.2 on 2025-07-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverassignment',
            name='truck',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.truckmodel'),
        ),
    ]
