# Generated by Django 5.1.2 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_driverassignment_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodel',
            name='tenure',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
